kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: /+nDZhuDM6B+VuQm81fyYYuSQbeKvoHGNlRZvpT2Aqo=
      - identity: {}
